### ISSUE TITLE
bitmap "calculator.ico" not defined

### ISSUE THREAD

**Issue by hacker-3342** [SarthakTools/Calculator#1]
Hello, just wanted to test this app on my PC and check it out. I installed the repository with the Github CLI, created a virtual environment and installed the customtkinter library. Didn't change anything in the code, just created a virtual environment. When running, I get the following error:
```
Traceback (most recent call last):
  File "c:\Users\Administrador\Documents\Calculator\Calculator\main.py", line 175, in <module>
    app = Calculator()
          ^^^^^^^^^^^^
  File "c:\Users\Administrador\Documents\Calculator\Calculator\main.py", line 7, in __init__
    self.iconbitmap("calculator.ico")
  File "C:\Users\Administrador\Documents\Calculator\env\Lib\site-packages\customtkinter\windows\ctk_tk.py", line 232, in iconbitmap
    super().wm_iconbitmap(bitmap, default)
  File "C:\Python312\Lib\tkinter\__init__.py", line 2156, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bitmap "calculator.ico" not defined
``` 
Any idea why this is failing?

**Comment by hacker-3342** [comment]
After a quick line fix, the program works as expected. Problem was I was running the code inside the project folder itself, where the README is located, instead of running it inside the Calculator folder where the icon file and python source code file is located. Sorry!
